### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Whatsie#195]
- [ ] Update *WhatsApp for Desktop* users
- [ ] Submit to [Ubuntu Software Center](https://myapps.developer.ubuntu.com/dev/apps/)
- [x] Submit to Arch Linux https://github.com/Aluxian/Whatsie/issues/60
- [ ] Submit to Mac App Store
- [ ] Submit to [Windows App Store](https://github.com/electron/electron/blob/master/docs/tutorial/windows-store-guide.md)

- ❌ Run without phone (not possible)

**Comment by bil-elmoussaoui** [comment]
Runing without phone is impossible, the messages are not storred on whatsapp server, you will need the phone to be connected to read the messages from it;)

**Comment by Aluxian** [comment]
I was thinking about running a headless Android instance in the background. Although this would be slow, complex to implement and consume a lot of disk and RAM, I think it'd be a great way to provide more value to users and make Whatsie even better than the official client.


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Fri, May 20, 2016 at 5:20 PM, Bilal Elmoussaoui < notifications@github.com [notifications@github.com] > wrote:
Runing without phone is impossible, the messages are not storred on whatsapp server, you will need the phone to be connected to read the messages from it;)

**Comment by halnine** [comment]
(if I understand correctly what you mean) Not sure if a headless Android instance can help - WhatsApp cannot work with 2 phones on the same phone# simultaniously, and it might void the phone's app verification.

**Comment by SalahAdDin** [comment]
Submit to arch linux oficial repositories :D

**Comment by Aluxian** [comment]
@halnine Right... I haven't thought of that. In that case, that feature is not even worth trying...

**Comment by SalahAdDin** [comment]
For now we can found facebookfordesktop and whatsappfordesktop in AUR.

**Comment by bil-elmoussaoui** [comment]
@SalahAdDin 
![capture du 2016-06-03 22-23-05](https://cloud.githubusercontent.com/assets/7660997/15791799/c290b7dc-29d9-11e6-9c53-067b1801b18a.png)

**Comment by Aluxian** [comment]
Yes, there *is* a package for Whatsie in AUR, but that's not published by me and it's not synced with my build process (its publisher uploads every version manually).

**Comment by bil-elmoussaoui** [comment]
You will need to contact him in order to fix that :) im an AUR packager,
ping me if you need any help :)
Le 4 juin 2016 07:21, "Alexandru Rosianu" <notifications@github.com> a
écrit :

**Comment by Aluxian** [comment]
Thanks, I'll ping you if I have questions :)

I'm already in touch with him, I (or someone who wants to help, maybe you?) just need to integrate publishing to AUR in the CI build step https://github.com/Aluxian/Whatsie/issues/60

**Comment by bil-elmoussaoui** [comment]
I just took a look, i think that you won't need all of that. You can use PKGBUILD file to get the latest version from Github releases automatically, download the deb file and install it ("convert it"). I can help if you want :+1:

**Comment by SalahAdDin** [comment]
Windows app store? wow.
